In [1]:
import numpy as np

In [7]:
import nibabel as nib

# Load the NIfTI file
img_hard_gt = nib.load("/data1/courses/2024-2025/4343SADL6/Tumor_Group/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/BraTS20_Training_006/BraTS20_Training_006_seg.nii")  # or .nii

# Get the image data as a NumPy array
img_data = img_hard_gt.get_fdata()  
print(img_data.shape)# shape: (H, W, D)

# Optional: get header or affine
affine_hard_gt = img_hard_gt.affine
header_hard_gt = img_hard_gt.header


(240, 240, 155)


In [8]:
img_soft_gt = nib.load("/data1/courses/2024-2025/4343SADL6/Tumor_Group/Datasets/BraTS_GeoLS/BraTS20_Training_006/BraTS20_Training_006_seg_transformed.nii.gz")  # or .nii

# Get the image data as a NumPy array
img_data = img_soft_gt.get_fdata()  
print(img_data.shape)# shape: (H, W, D)

# Optional: get header or affine
affine_soft_gt = img_soft_gt.affine
header_soft_gt = img_soft_gt.header


(240, 240, 155)


In [10]:
print(affine_hard_gt)

[[ -1.  -0.  -0.   0.]
 [ -0.  -1.  -0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]


In [9]:
print(affine_soft_gt)

[[ -1.   0.   0.  -0.]
 [  0.  -1.   0. 239.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]


In [ ]:
print(header_hard_gt)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 240 155   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : 0.0
qoffset_y       : 239.0
qoffset_z       : 0.0
srow_x          : [-1. -0. -0.  0.]
srow_y          : [

In [11]:
print(header_soft_gt)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 240 240 155   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : uint8
bitpix          : 8
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : -0.0
qoffset_y       : 239.0
qoffset_z       : 0.0
srow_x          : [-1.  0.  0. -0.]
srow_y          : 

In [2]:
image_hard_label = np.array("/data1/courses/2024-2025/4343SADL6/Tumor_Group/BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/BraTS20_Training_006/BraTS20_Training_006_seg.nii")

In [3]:
print(image_hard_label.shape)

()
